#!/bin/sh

for SCRIPT in '~/.bash_profile' '~/.zshrc' '~/.cshrc'
do
	gem list | grep xcodeproj > /dev/null
	if [ $? -ne 0 ]; then
		if [ -f "$SCRIPT" ] ; then
		. "$SCRIPT"
		fi
	fi
done

gem list | grep xcodeproj > /dev/null
if [ $? -ne 0 ]; then
	gem install xcodeproj
	if [ $? -ne 0 ]; then
		sudo gem install xcodeproj
	fi
fi

ruby ./Assets/Editor/install.rb -y -o -l ./Assets/Plugins/iOS/GrowthPush.framework -p $1
