#!/bin/sh

if [ -f ~/.bash_profile ] ; then
. ~/.bash_profile
fi

gem list | grep xcodeproj > /dev/null
if [ $? -ne 0 ]; then
	gem install xcodeproj
	if [ $? -ne 0 ]; then
		sudo gem install xcodeproj
	fi
fi

ruby ./Assets/Editor/install.rb -y -o -l ./Assets/Plugins/iOS/GrowthPush.framework -p $1
