#!/bin/bash

TOOL_DIR=`dirname $0`
ROOT_DIR="${TOOL_DIR}/../"
FILES=( \ 
	'README.md' \ 
	'LICENSE' \ 
	'CHANGES' \ 
	'growthpush.unitypackage' \ 
)

for FILE in ${FILES[@]}; do
	echo -n "Check ${FILE}... "
	if [ -f ${ROOT_DIR}/${FILE} ]; then
		echo 'exists.'
	elif [ -d ${ROOT_DIR}/${FILE} ]; then
		echo 'exists.'
	else
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

SUBMODULES=( \ 
	'growthpush-ios' \ 
	'growthpush-android' \ 
)

for SUBMODULE in ${SUBMODULES[@]}; do
	echo -n "Check submodule ${SUBMODULE}... "
	${ROOT_DIR}/submodules/${SUBMODULE}/tools/verify
	if [ $? -ne 0 ]; then
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

echo '[SUCCESS] Completed to verify package.'
